plugins:
  fixme:
    enabled: true
  sass-lint:
    enabled: false
  markdownlint:
    enabled: false
  scss-lint:
    enabled: true
  phpcodesniffer:
    enabled: true
    checks:
      Generic Files LineLength TooLong:
        enabled: false
