# Project language
language: php

# Language version
php: '7.1'

# Cache config
cache:
  yarn: true
  directories:
    - $HOME/.composer/cache/files
    - ./bin/.phpunit

# Update composer
before_install:
  - composer self-update

# Install project, dependencies & testing suite
install:
  - composer install
  - cp .env.test .env
  - ./bin/phpunit install
  - yarn install

# Build assets
before_script:
  - yarn encore dev

# Run tests
script:
  - ./bin/phpunit
  # this checks that the YAML config files contain no syntax errors
  - ./bin/console lint:yaml config --parse-tags
  # this checks that the Twig template files contain no syntax errors
  - ./bin/console lint:twig templates --env=prod
  # this checks that the XLIFF translations contain no syntax errors
  - ./bin/console lint:xliff translations
  # this checks that the application doesn't use dependencies with known security vulnerabilities
  - ./bin/console security:check
  # this checks that Doctrine's mapping configurations are valid
  - ./bin/console doctrine:schema:validate --skip-sync -vvv --no-interaction
